name: Build Android APK

on:
  release:
    types: [created, published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Build APK
        run: flet build apk --yes

      - name: Rename APk with Date and Build number
        run: |
          BUILD_DATE=$(date +'%Y-%m-%d')
          BUILD_NUM="${{ github.run_number }}"
          NEW_NAME="ModuFlexCLI-b${BUILD_NUM}_${BUILD_DATE}.apk"

          mkdir -p release_apk
          cp build/apk/*.apk "release_apk/${NEW_NAME}"

          echo "APK_FILE_PATH=release_apk/${NEW_NAME}" >> $GITHUB_ENV

      - name: Upload APK to created Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.APK_FILE_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
